Algoritmo "Lista 2 - Atividade 1"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 28/08/2024
Var
// variaveis
   a,b : inteiro

Inicio
// inicio do programa
   escreval ("Digite o valor para A e B")
   leia(a,b)
   se (a = b) entao
      escreval ("A e B são Iguais")
   senao
      escreval ("A e B são Diferentes")
   fimse

Fimalgoritmo