Algoritmo "Lista 2 - Atividade 7"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 28/08/2024
Var
// variaveis
   a, b : inteiro

Inicio
// inicio do programa
   escreval ("Escreva os valor de A e B")
   leia (a , b)
   
   se (a = b) entao
      escreval ("Igual")

   senao

      se (a > b) então
         escreval ("Maior")

      senao
         escreval ("Menor")

      fimse
   fimse
Fimalgoritmo
