Algoritmo "Lista 2 - Atividade 3"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 28/08/2024
Var
// variaveis
   a, b, c, media : real

Inicio
// inicio do programa
   escreval ("Digite suas três notas")
   leia (a, b, c)

   media <- (a + b + c)/3

   se (media = 10) então
      escreval ("Nota Maxima")
      
   senao
      escreval ("Outro Valor")

   fimse

Fimalgoritmo