Algoritmo "Atividade 6"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 07/08/2024
Var
// Define as Variaveis
v,t: real

Inicio
// inicio do programa

//Define a Variavel de Tempo
escreva ("Qual foi o tempo do trajeto? ")
leia (t)

//Atribui a velocidade média a variavel V
v <- 30/t
escreva ("Sua velocidade média foi de ", v, " Km/h")

Fimalgoritmo