Algoritmo "Atividade 1"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 07/08/2024
Var
// variaveis
PF, PC: real

Inicio
// inicio do programa
escreva ("Digite o valor de compra: ")

//define o valor da variavel PC
leia (PC)

//define o valor de PF
PF <- PC + (55*PC/100)

//Mostra o valor do PF na tela
escreval ("O preço de venda é: ", PF, " R$")

Fimalgoritmo