Algoritmo "Atividade 3"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 07/08/2024
Var
// variaveis
PV, PF: real

Inicio
// inicio do programa
escreva ("Qual o valor do produto ? ")

//define o valor da veriavel PV
leia (PV)

//define o valor de PF
PF <- PV - (15*PV/100)

//Monstra o valor do PF na tela
escreval ("O preço de venda é: ", PF, " R$")

Fimalgoritmo