Algoritmo "Atividade 7"
// Disciplina   : Algoritimos
// Professor   : JOHN SOLDERA
// Autor(a)    : BRIAN WEBER
// Data atual  : 07/08/2024
Var
// Define as Variaveis
p,m: real

Inicio
// inicio do programa

//Define a variavel p
p <- 150000 / 12

//Define a Variavel m
escreva ("Quantos meses tem de produção? ")
leia (m)

//Mostra na tela a produção naquele periodo de meses
escreva ("Sua produção em ", m, " meses vai ser de ", p * m, " Toneladas.")

Fimalgoritmo